package_assets: on

javascripts:
    all:
        - public/javascripts/vendor/jquery.min.js
        - public/javascripts/vendor/date.js
        - public/javascripts/vendor/mustache.js
        - public/javascripts/vendor/bootstrap-dropdown.js
        - public/javascripts/vendor/bootstrap-modal.js
        - public/javascripts/tt-core.js
        - public/javascripts/tt-util.js
        - public/javascripts/tt-data.js
        - public/javascripts/tt-form.js
        - public/javascripts/tt-component.js
        - public/javascripts/tt-manager.js
    
    home:    
        - public/javascripts/widgets/tt-timer.js
        - public/javascripts/components/tt-title.js
        - public/javascripts/components/tt-newentry.js
        - public/javascripts/components/tt-entries.js

    signup:
        - public/javascripts/components/tt-signup.js

    login:
        - public/javascripts/components/tt-login.js
    
    newinvoice:
        - public/javascripts/widgets/tt-slider.js
        - public/javascripts/components/tt-newinvoice.js
    
    invoice:
        - public/javascripts/components/tt-invoice.js

stylesheets:
    all:
        - public/stylesheets/vendor/bootstrap.min.css
        - public/stylesheets/tt-core.css
        - public/stylesheets/tt-layout.css
        - public/stylesheets/tt-widgets.css
    
    home:
        - public/stylesheets/tt-home.css
    
    newinvoice:
        - public/stylesheets/tt-newinvoice.css
    
    invoice:
        - public/stylesheets/tt-invoice.css